# Generated by Django 6.0.4 on 2026-04-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='non_member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='non_member_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_management_system.member'),
        ),
    ]
